---
version: 2
updates:

  ## Go mod

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependabot"
      - "go"
      - "type::security"

  ## GitHub Actions

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot"
      - "github-actions"
      - "type::security"
