apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "kots-sdk.labels" . | nindent 4 }}
  name: {{ include "kots-sdk.fullname" . }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: 3000
  selector:
    app: kots-sdk
  type: {{ .Values.service.type }}
