{{ if not .Values.minimalRBAC }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "replicated.labels" . | nindent 4 }}
  name: replicated-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: replicated-role
subjects:
- kind: ServiceAccount
  name: replicated
  namespace: {{ .Release.Namespace }}
{{ end }}