{{ if and (not .Values.serviceAccountName) (not .Values.clusterRole) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "replicated.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
  name: {{ include "replicated.roleName" . }}
  namespace: {{ include "replicated.namespace" . | quote }}
rules:
{{ if not .Values.minimalRBAC }}
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - 'get'
  - 'list'
  - 'watch'
{{ end }}
- apiGroups:
  - ''
  resources:
  - 'secrets'
  verbs:
  - 'create'
- apiGroups:
  - ''
  resources:
  - 'secrets'
  verbs:
  - 'update'
  resourceNames:
  - {{ include "replicated.secretName" . }}
  - replicated-instance-report
  - replicated-custom-app-metrics-report
  - replicated-meta-data
{{ if .Values.minimalRBAC }}
# Get, list, and watch deployments, statefulsets, and daemonsets for Service Monitors
- apiGroups:
  - "apps"
  resources:
  - "deployments"
  - "statefulsets"
  - "daemonsets"
  verbs:
  - "get"
  - "list"
  - "watch"
# List pods as part of statefulset and daemonset service monitors
- apiGroups:
  - ""
  resources:
  - "pods"
  verbs:
  - "list"
# Get, list, and watch ingresses for Service Monitors
- apiGroups:
  - "networking.k8s.io"
  resources:
  - "ingresses"
  verbs:
  - "get"
  - "list"
  - "watch"
# Get, list, and watch persistentvolumeclaims, services, and endpoints for Service Monitors
- apiGroups:
  - ""
  resources:
  - "persistentvolumeclaims"
  - "services"
  - "endpoints"
  verbs:
  - "get"
  - "list"
  - "watch"
{{ end }}
{{ end }}
