{{/*
Renders the Support Bundle secret to be used by the Replicated SDK
*/}}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "replicated-sdk.labels" . | nindent 4 }}
    troubleshoot.io/kind: support-bundle
  name: replicated-sdk-supportbundle
stringData:
  support-bundle-spec: |-
    apiVersion: troubleshoot.sh/v1beta2
    kind: SupportBundle
    metadata:
      name: replicated-sdk-supportbundle
    spec:
      collectors:
        - logs:
            collectorName: replicated-sdk-logs
            selector:
              {{- include "replicated-sdk.labels" . | nindent 14 }}
            name: replicated-sdk/logs
