apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "replicated-sdk.labels" . | nindent 4 }}
  name: replicated-sdk
spec:
  selector:
    matchLabels:
      {{- include "replicated-sdk.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "replicated-sdk.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: replicated-sdk
        secret:
          secretName: replicated-sdk
      containers:
      - name: replicated-sdk
        image: {{ index .Values.images "replicated-sdk" }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: replicated-sdk
          mountPath: /etc/replicated-sdk/config.yaml
          readOnly: true
          subPath: config.yaml
        env:
        - name: REPLICATED_SDK_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: IS_HELM_MANAGED
          value: "true"
        - name: HELM_RELEASE_NAME
          value: {{ .Release.Name }}
        - name: HELM_RELEASE_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: HELM_RELEASE_REVISION
          value: {{ .Release.Revision | quote }}
        - name: HELM_PARENT_CHART_URL
          value: {{ .Values.parentChartURL | default "" | quote }}
        - name: HELM_DRIVER
          value: secret # TODO: support other drivers
        - name: REPLICATED_SDK_CONFIG_FILE
          value: /etc/replicated-sdk/config.yaml
        {{- if (.Values.integration).licenseID }}
        - name: REPLICATED_SDK_INTEGRATION_LICENSE_ID
          valueFrom:
            secretKeyRef:
              name: replicated-sdk
              key: integration-license-id
        {{- end }}
        ports:
        - containerPort: 3000
          name: http
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      serviceAccountName: {{ .Values.serviceAccountName | default "replicated-sdk" }}
status: {}
