{{ if not .Values.serviceAccountName }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "replicated.labels" . | nindent 4 }}
  name: {{ include "replicated.roleName" . }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - 'get'
  - 'list'
  - 'watch'
- apiGroups:
  - ''
  resources:
  - 'configmaps'
  verbs:
  - 'update'
  resourceNames:
  - {{ include "replicated.configMapName" . }}
- apiGroups:
  - ''
  resources:
  - 'secrets'
  verbs:
  - 'update'
  resourceNames:
  - {{ include "replicated.secretName" . }}
{{ end }}