{{ if not .Values.serviceAccountName }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "replicated-sdk.labels" . | nindent 4 }}
  name: replicated-sdk-role
  namespace: {{ include "replicated-sdk.namespace" . | quote }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - 'get'
  - 'list'
  - 'watch'
- apiGroups:
  - ''
  resources:
  - 'configmaps'
  - 'secrets'
  verbs:
  - 'update'
  resourceNames:
  - replicated-sdk
{{ end }}