apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "replicated-sdk.labels" . | nindent 4 }}
  name: replicated-sdk
  namespace: {{ include "replicated-sdk.namespace" . | quote }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: 3000
  selector:
    {{- include "replicated-sdk.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
