{{ if not .Values.serviceAccountName }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "replicated.labels" . | nindent 4 }}
  name: {{ include "replicated.roleName" . }}
  namespace: {{ include "replicated.namespace" . | quote }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - 'get'
  - 'list'
  - 'watch'
- apiGroups:
  - ''
  resources:
  - 'secrets'
  verbs:
  - 'create'
- apiGroups:
  - ''
  resources:
  - 'secrets'
  verbs:
  - 'update'
  resourceNames:
  - {{ include "replicated.secretName" . }}
  - replicated-instance-report
  - replicated-custom-app-metrics-report
  - replicated-meta-data
{{ end }}