{{- if not .Values.readOnlyMode }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "replicated.labels" . | nindent 4 }}
    replicated.com/resource: support-bundle-metadata
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
  name: replicated-support-metadata
  namespace: {{ include "replicated.namespace" . | quote }}
type: Opaque
{{- end }}
