apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "replicated-sdk.labels" . | nindent 4 }}
  name: replicated-sdk
type: Opaque
stringData:
  config.yaml: |
    license: {{- .Values.license | toYaml | indent 4 }}
    licenseFields: 
      {{- include "replicated-sdk.licenseFields" . | nindent 6 }}
    appName: {{ .Values.appName | default "" | quote }}
    channelID: {{ .Values.channelID | default "" | quote }}
    channelName: {{ .Values.channelName | default "" | quote }}
    {{- if .Values.channelSequence }}
    channelSequence: {{ .Values.channelSequence }}
    {{- end }}
    {{- if .Values.releaseSequence }}
    releaseSequence: {{ .Values.releaseSequence }}
    {{- end }}
    releaseCreatedAt: {{ .Values.releaseCreatedAt | default "" | quote }}
    releaseNotes: |-
      {{- .Values.releaseNotes | default "" | nindent 6 }}
    versionLabel: {{ .Values.versionLabel | default "" | quote }}
    replicatedAppEndpoint: {{ .Values.replicatedAppEndpoint | default "" | quote }}
    {{- if .Values.statusInformers }}
    statusInformers:
      {{- .Values.statusInformers | toYaml | nindent 6 }}
    {{- end }}
  {{- if (.Values.integration).licenseID }}
  integration-license-id: {{ .Values.integration.licenseID }}
  {{- end }}
  # kindIs "invalid" indicates that the value is nil and the user did not provide a value
  {{- if not (kindIs "invalid" (.Values.integration).enabled) }}
  integration-enabled: "{{ (.Values.integration).enabled }}"
  {{- end }}
  {{- if (.Values.integration).mockData }}
  integration-mock-data: {{- .Values.integration.mockData | toYaml | indent 1 }}
  {{- end }}
