# Default values for test chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  name: ""

service:
  type: ClusterIP
  port: 80

replicated:
  statusInformers:
    - deployment/test-chart
    - deployment/replicated
    - service/test-chart
    - service/replicated
    - daemonset/test-daemonset
    - statefulset/test-statefulset
    - pvc/test-storage-test-statefulset-0