contents:
  repositories:
    - https://apk.cve0.io
  keyring:
    - https://apk.cve0.io/key/cve0-signing.rsa.pub
  packages:
    - replicated
    - bash
    - busybox-bootstrap-1.36
    - curl

accounts:
  groups:
    - groupname: replicated
      gid: 1001
  users:
    - username: replicated
      uid: 1001
      gid: 1001
  run-as: replicated

environment:
  VERSION: 1.0.0

entrypoint:
  command: /replicated api
