contents:
  repositories:
    - https://packages.wolfi.dev/os
    - ./packages/
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    - ./melange.rsa.pub
  packages:
    - replicated  # This is expected to be built locally by `melange`.
    - bash
    - busybox
    - curl
    - wolfi-baselayout

accounts:
  groups:
    - groupname: replicated
      gid: 1001
  users:
    - username: replicated
      uid: 1001
      gid: 1001
  run-as: replicated

environment:
  VERSION: 1.0.0

entrypoint:
  command: /replicated api
