name: Import secrets and variables to Depot CI
on: push

permissions:
  id-token: write
  contents: read

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: depot/setup-action@v1
      - name: Import secrets
        env:
          C11Y_MATRIX_TOKEN: ${{ secrets.C11Y_MATRIX_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
          OP_SERVICE_ACCOUNT: ${{ secrets.OP_SERVICE_ACCOUNT }}
          OP_SERVICE_ACCOUNT_PRODUCTION: ${{ secrets.OP_SERVICE_ACCOUNT_PRODUCTION }}
          REPLICATED_PASS_PROD: ${{ secrets.REPLICATED_PASS_PROD }}
          REPLICATED_PASS_STAGING: ${{ secrets.REPLICATED_PASS_STAGING }}
          REPLICATED_USER_PROD: ${{ secrets.REPLICATED_USER_PROD }}
          REPLICATED_USER_STAGING: ${{ secrets.REPLICATED_USER_STAGING }}
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
          OKTETO_TOKEN: ${{ secrets.OKTETO_TOKEN }}
          PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
          REPLICATED_GH_PAT: ${{ secrets.REPLICATED_GH_PAT }}
        run: |
          unset DEPOT_TOKEN
          depot ci secrets add C11Y_MATRIX_TOKEN="$C11Y_MATRIX_TOKEN" GH_PAT="$GH_PAT" OP_SERVICE_ACCOUNT="$OP_SERVICE_ACCOUNT" OP_SERVICE_ACCOUNT_PRODUCTION="$OP_SERVICE_ACCOUNT_PRODUCTION" REPLICATED_PASS_PROD="$REPLICATED_PASS_PROD" REPLICATED_PASS_STAGING="$REPLICATED_PASS_STAGING" REPLICATED_USER_PROD="$REPLICATED_USER_PROD" REPLICATED_USER_STAGING="$REPLICATED_USER_STAGING" DAGGER_CLOUD_TOKEN="$DAGGER_CLOUD_TOKEN" DD_API_KEY="$DD_API_KEY" DOCKERHUB_PASSWORD="$DOCKERHUB_PASSWORD" DOCKERHUB_USER="$DOCKERHUB_USER" FOSSA_API_KEY="$FOSSA_API_KEY" OKTETO_TOKEN="$OKTETO_TOKEN" PACT_BROKER_BASE_URL="$PACT_BROKER_BASE_URL" PACT_BROKER_TOKEN="$PACT_BROKER_TOKEN" REPLICATED_GH_PAT="$REPLICATED_GH_PAT" --repo replicatedhq/replicated-sdk
  variables:
    runs-on: ubuntu-latest
    steps:
      - uses: depot/setup-action@v1
      - name: Import variables
        env:
          PACT_BROKER_BASE_URL: ${{ vars.PACT_BROKER_BASE_URL }}
        run: |
          unset DEPOT_TOKEN
          depot ci vars add PACT_BROKER_BASE_URL="$PACT_BROKER_BASE_URL" --repo replicatedhq/replicated-sdk
