name: Release CVE Scan
on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC daily
  workflow_dispatch:      # Allow manual triggers

jobs:
  scan-release:
    name: Scan Current Release
    runs-on: ubuntu-latest
    permissions:
      security-events: write  # Required for uploading SARIF results
      
    steps:
      - name: Get latest release
        id: get_release
        uses: actions/github-script@v6
        with:
          script: |
            const release = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            core.setOutput('tag_name', release.data.tag_name);

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'index.docker.io/replicated/replicated-sdk:${{ steps.get_release.outputs.tag_name }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'release-cve-scan'