name: Release CVE Scan

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC daily
  workflow_dispatch:      # Allow manual triggers

jobs:
  scan-release:
    name: Scan Current Release
    runs-on: ubuntu-latest
    permissions:
      security-events: write  # Required for uploading SARIF results
      
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'index.docker.io/replicated/replicated-sdk:${{ github.event.repository.latest_release.tag_name }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'release-cve-scan' 